services:
  # RabbitMQ with management console
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "1883:1883"   # MQTT protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpassword
    volumes:
      - ./rabbitmq-config/enabled_plugins:/etc/rabbitmq/enabled_plugins

  # PostgreSQL (Aurora PostgreSQL compatible)
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aurora_db
  charge_point_selector:
    container_name: charge_point_selector
    image: charge-point-selector:latest
    depends_on:
      - rabbitmq
      - postgres
    environment:
      APP_ENVIRONMENT: "local"
      MQTT.INSECURE: true
      MQTT.CONNECT.HOST: "rabbitmq"
      MQTT.CONNECT.USERNAME: "admin"
      MQTT.CONNECT.PASSWORD: "adminpassword"
      SERVER.HOST: "::"
      SERVER.PORT: 3333
      ENSURE_STATE: true
      DATABASE.WRITE.HOST: "postgres"
      DATABASE.READ.HOST: "postgres"
      DATABASE.USERNAME: "postgres"
      DATABASE.PASSWORD: "postgres"
      DATABASE.NAME: "aurora_db"
    ports:
      - "3333:3333"
  simulator:
    container_name: simulator
    image: charge-point-selector-evse-simulator:latest
    depends_on:
      - rabbitmq
    environment:
      APP_ENVIRONMENT: "local"
      MQTT.INSECURE: true
      MQTT.CONNECT.HOST: "rabbitmq"
      MQTT.CONNECT.USERNAME: "admin"
      MQTT.CONNECT.PASSWORD: "adminpassword"
      SERVER.PORT: 7420
    ports:
      - "7420:7420"
